version: "0.2.0"
sku:
  AMERICANO:
    display: "아메리카노"
    synonyms: ["아이스 아메리카노", "아아", "뜨아", "아메리카노"]
    options:
      size: [S, M, L]
      temp: [ICE, HOT]
  LATTE:
    display: "카페라떼"
    synonyms: ["라떼", "카페라떼", "카페 라떼", "라떼 아이스", "아이스 라떼", "뜨거운 라떼"]
    options:
      size: [S, M, L]
      temp: [ICE, HOT]
  VANILLA_LATTE:
    display: "바닐라 라떼"
    synonyms: ["바닐라라떼", "아이스 바닐라라떼", "바닐라 라떼"]
    options:
      size: [S, M, L]
      temp: [ICE, HOT]
